import { PrebuiltPromotionPreset } from "./types";

export const PREBUILT_PROMOTION_PRESETS: PrebuiltPromotionPreset[] = [
  {
    id: "diwali_festive_sparkle",
    title: "Diwali & Festive Sparkle Sale",
    subtitle: "Site-wide 20% OFF on Luxury Lighting",
    description:
      "Applies 20% discount on all orders above ₹10,000. Includes Google Merchant Center feed sync, Meta Ads offer sync, and email blast.",
    badge: "20% OFF",
    badgeBg: "bg-amber-500/10 text-amber-400 border-amber-500/30",
    codePrefix: "FESTIVE20",
    type: "PERCENTAGE",
    value: 20,
    minOrderAmount: 10000,
    maxDiscountCap: 5000,
    durationDays: 14,
    usageLimitPerUser: 1,
    targetChannels: {
      googleMerchant: true,
      metaCommerce: true,
      emailBlast: true,
      webPush: true,
    },
    iconName: "Zap",
  },
  {
    id: "white_glove_free_shipping",
    title: "White-Glove Shipping & Installation",
    subtitle: "Complimentary Delivery on Orders > ₹5,000",
    description:
      "Waives shipping and white-glove setup charges across India. High conversion booster for high-ticket chandeliers and floor lamps.",
    badge: "FREE SHIPPING",
    badgeBg: "bg-emerald-500/10 text-emerald-400 border-emerald-500/30",
    codePrefix: "FREESHIP",
    type: "FREE_SHIPPING",
    value: 0,
    minOrderAmount: 5000,
    durationDays: 30,
    usageLimitPerUser: 2,
    targetChannels: {
      googleMerchant: true,
      metaCommerce: true,
      emailBlast: false,
      webPush: true,
    },
    iconName: "Plane",
  },
  {
    id: "architect_b2b_privilege",
    title: "Architect & Designer B2B Privilege",
    subtitle: "15% Trade Privilege + 5% Affiliate Attribution",
    description:
      "Exclusive promotion for interior designers, architects, and hospitality buyers purchasing bulk lighting.",
    badge: "15% B2B TRADE",
    badgeBg: "bg-purple-500/10 text-purple-400 border-purple-500/30",
    codePrefix: "ARCHITECT15",
    type: "PERCENTAGE",
    value: 15,
    minOrderAmount: 25000,
    durationDays: 60,
    usageLimitPerUser: 5,
    targetChannels: {
      googleMerchant: false,
      metaCommerce: true,
      emailBlast: true,
      webPush: false,
    },
    iconName: "Users",
  },
  {
    id: "flash_clearance_blitz",
    title: "24-Hour Flash Clearance Blitz",
    subtitle: "Flat ₹2,000 OFF on Orders > ₹15,000",
    description:
      "Urgency-driven 24-hour flash sale for ready-to-ship luxury inventory with live stock counter.",
    badge: "FLAT ₹2,000 OFF",
    badgeBg: "bg-red-500/10 text-red-400 border-red-500/30",
    codePrefix: "FLASH2000",
    type: "FIXED_AMOUNT",
    value: 2000,
    minOrderAmount: 15000,
    durationDays: 1,
    usageLimitPerUser: 1,
    targetChannels: {
      googleMerchant: true,
      metaCommerce: true,
      emailBlast: true,
      webPush: true,
    },
    iconName: "Ticket",
  },
  {
    id: "chandelier_sconce_bundle",
    title: "Chandelier & Wall Sconce Bundle",
    subtitle: "Flat ₹1,500 OFF Matching Sconces",
    description:
      "Cross-sell promo triggering ₹1,500 instant discount when purchasing statement chandeliers with matching sconces.",
    badge: "₹1,500 BUNDLE",
    badgeBg: "bg-blue-500/10 text-blue-400 border-blue-500/30",
    codePrefix: "LUXEBUNDLE",
    type: "FIXED_AMOUNT",
    value: 1500,
    minOrderAmount: 12000,
    durationDays: 21,
    usageLimitPerUser: 1,
    targetChannels: {
      googleMerchant: true,
      metaCommerce: true,
      emailBlast: false,
      webPush: false,
    },
    iconName: "Tag",
  },
  {
    id: "first_time_welcome_voucher",
    title: "First-Time Buyer Welcome Privilege",
    subtitle: "10% Welcome Discount (Max ₹1,500)",
    description:
      "Automated onboarding coupon for new visitors registering an account on James & Sons storefront.",
    badge: "10% WELCOME",
    badgeBg: "bg-cyan-500/10 text-cyan-400 border-cyan-500/30",
    codePrefix: "WELCOME10",
    type: "PERCENTAGE",
    value: 10,
    minOrderAmount: 3000,
    maxDiscountCap: 1500,
    durationDays: 90,
    usageLimitPerUser: 1,
    targetChannels: {
      googleMerchant: true,
      metaCommerce: false,
      emailBlast: true,
      webPush: true,
    },
    iconName: "CheckCircle2",
  },
];
